### PR TITLE
Update SportStatisticTest.java

### PR DESCRIPTION
**Pull request by ghost**
I believe the reference to superman in winsAndLosses2() may be a mistake, in winsAndLosses3() superman is supposed to have won a game (this is throwing up an error on my project).

### CODE REVIEW

**Comment by cardouken** [comment]
If you look above to see what it's asserting against, the tests seem to be correct. First instance:

`cats,mice,32,34
batman,superman,30,31
batman,robin,1,0
cats,dogs,3,0`

cats won once, so it should contain that line.

Second instance:

`bestTeam,superteam,32,34
batman,superman,30,31
batman,robin,1,0
cats,dogs,3,0`

superman lost once, haven't won once

I downloaded the latest version from TMC to see if they may have changed anything compared to the versions up here, but it's still identical. The tests pass just fine on my end (just make sure to run maven clean and maven test before running locally as otherwise all tests will probably fail). Also, they should pass when you submit them to TMC regardless.

**Comment by cardouken** [comment]
I agree that some tests are pretty scuffed, especially when it comes to clarity in terms of what they're trying to do (+ having to maven clean/test every single time) they should still be passing as-is.

`winsAndLosses2()` is asserting the result against `io.getSysOut()` which produces:

File:
Team:
Games: 2
Wins: 1
Losses: 1

The assertion here is to find a line from this output containing 1 win and 1 loss from the stream operations in the condition arguments. The included message is definitely wrong but it's only used to produce an error message on why the test failed in case it does and doesn't change the actual test logic.

`winsAndLosses3()` has the exact same underlying logic but it's actually asserting against a non-existent team called spiderman so the result of 0 wins and 0 losses is expected, as such a team cannot be found in the first place. So the failure messages on lines 133 and 134 should be changed to `When searcing for spiderman the output should have the line` instead of `searching for superman`. But again, these don't change whether the test passes or not.

If you're having issues with tests passing locally, try undoing the changes you made, running maven clean and maven test (and locally afterwards if you'd like) - they should work. Also, MOOC.fi-s server should accept this solution just fine.

I posted these solutions with their tests as a carbon copy from what was produced by MOOC.fi-s TMC plugin. So these fixes should probably submitted to the team at MOOC.fi instead as I don't want to alter anything that was already originally there, even if it was a mistake since I'm not affiliated with them in any way. The solution should pass though since these are unit tests and don't test the actual solution at all.

**Comment by ghost** [comment]
Thanks for the response, yeah it turns out I wasn't outputting the wins and
losses for a non-existent team, but the tests outputs are a bit of a mess
making it confusing identifying the issue. Also sorry I didn't realise your
repo wasn't Mooc.fi's, still getting used to github.

**Comment by cardouken** [comment]
@jacknix1 no worries, it took me a good few minutes to realize what was actually wrong as well. There are some lazy mistakes left in the code and I'm not sure if they'd fix them considering they don't actually break anything but you can try getting in touch with them directly via: https://java-programming.mooc.fi/credits

Closing this PR for now, hope my explanation helped at least somewhat.

**Pull request closed without merging**
